--[[
	Defines the data representing a blast created by the laser blaster.

	Generated by the Client in generateBlastData.
--]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local RayResult = require(ReplicatedStorage.LaserRay.RayResult)

local BlastData = {}

export type Type = {
	player: Player,
	originCFrame: CFrame,
	rayResults: { RayResult.Type },
}

return BlastData
